### ISSUE TITLE
Question Regarding per_device_train_batch_size and gradient_accumulation_steps in LLaVA Training

### ISSUE THREAD

**Issue by jinpeng0528** [zackschen/CoIN#13]
Hi Zacks,

Thank you for this amazing work!

I have a question regarding the LLaVA training configuration across different tasks in the LLaVA project. I noticed that the `per_device_train_batch_size` is set to various values such as 6, 8, 14, and 16, and the `gradient_accumulation_steps` is consistently set to 8. These settings differ significantly from the default configuration in LLaVA's official `finetune_lora.sh`.

Could you please clarify whether these values were chosen due to GPU memory constraints, or were they specifically tuned to optimize performance? Additionally, if I have sufficient GPU memory, would you recommend sticking to these settings, or should I consider different configurations?

Thank you in advance for your guidance!

**Comment by zackschen** [comment]
Hi, jinpeng,

Indeed,  we set different batch sizes purely due to GPU memory issues, not to get particular performance. 
Because different datasets have different sample sizes that each batch can hold. 
We based our settings on our 24G GPU memory, if you have a bigger GPU, you can set a bigger batch size, or use the settings recommended by llava.

**Comment by jinpeng0528** [comment]
Thank you so much for your quick reply!
